In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [92]:
path ='./data/'

books = pd.read_csv(path + 'books.csv')

In [93]:
def basic_preporcess_category(s:str):
    if isinstance(s, str):
        return s.lower().strip('[] !@#$%^&*()\"\';:.,/?\\|~`')
    elif isinstance(s, float):
        return np.nan
    else:
        raise Exception("WTF")

In [94]:
books['category'] = books['category'].apply(lambda x: basic_preporcess_category(x))

In [95]:
# 처리하기 전의 category_high
books['category_high'] = books['category'].copy()

books.loc[books[books['category']=='biography'].index, 'category_high'] = 'biography autobiography'
books.loc[books[books['category']=='autobiography'].index,'category_high'] = 'biography autobiography'
books.loc[books[books['category'].str.contains('history',na=False)].index,'category_high'] = 'history'

categories = ['garden','crafts','physics','adventure','music','fiction','nonfiction','science','science fiction','social','homicide',
'sociology','disease','religion','christian','philosophy','psycholog','mathemat','agricult','environmental',
'business','poetry','drama','literary','travel','motion picture','children','cook','literature','electronic',
'humor','animal','bird','photograph','computer','house','ecology','family','architect','camp','criminal','language','india']
for category in categories:
    books.loc[books[books['category'].str.contains(category,na=False)].index,'category_high'] = category

category_high_df = pd.DataFrame(books['category_high'].value_counts()).reset_index()
category_high_df.columns = ['category','count']
# others_list = category_high_df[category_high_df['count']<3]['category'].values
# books.loc[books[books['category_high'].isin(others_list)].index, 'category_high']='others'
# books.drop('category', axis=1, inplace=True)

In [96]:
books['category_high'].value_counts().to_frame()

                                                    category_high
fiction                                                     39678
biography & autobiography                                    3326
history                                                      1949
religion                                                     1824
nonfiction                                                   1427
...                                                           ...
persian gulf                                                    1
procedure (law                                                  1
chicken pox                                                     1
kites                                                           1
authors, canadian (english) 20th century biography              1

[3265 rows x 1 columns]

In [97]:
list_of_words = list(books['category_high'].unique())
list_of_words = list_of_words[:5] + list_of_words[6:]

In [98]:
for idx, word in enumerate(list_of_words):
    if not isinstance(word, str):
        print(word)
        print(type(word))
        print("---")

In [99]:
import re

list_of_words = ' '.join(list_of_words)

list_of_words = (re.sub('[^a-zA-Z]', ' ', list_of_words)).split()

for idx, word in enumerate(list_of_words):
    while ('  ' in word):
        list_of_words[idx].replace('  ', ' ')

In [ ]:
from collections import Counter
cnt_of_words = Counter(list_of_words)

In [105]:
df_of_words = pd.DataFrame(list(cnt_of_words.items()), columns=['word', 'count'])

In [110]:
df_of_words.sort_values(by=['count'], ascending=[False])

            word  count
23     character    164
22    fictitious    162
88           and    133
132     american     53
90       stories     52
...          ...    ...
1590     skating      1
1591      gender      1
1592        iowa      1
1593  industrial      1
3649    deafness      1

[3650 rows x 2 columns]

In [111]:
df_of_words_ = df_of_words[df_of_words['count'] > 20]

In [113]:
df_of_words_.sort_values(by=['count'], ascending=[False])

           word  count
23    character    164
22   fictitious    162
88          and    133
132    american     53
90      stories     52
422          in     37
16           of     36
62        books     34
131     authors     33
35      england     31
79        women     31
230         art     29
234  television     29
304           n     23
173     african     22

In [115]:
cnt_little_category = list()
for cnt in range(2,6):
    cnt_little_category.append(category_high_df[category_high_df['count']<cnt])
    if cnt > 2:
        print(len(cnt_little_category[-1]) - len(cnt_little_category[-2]))
    else:
        print(len(cnt_little_category[-1]))

2034
473
228
118

In [121]:
path ='./data/'

books = pd.read_csv(path + 'books.csv')
def basic_preporcess_category(s:str):
    if isinstance(s, str):
        return s.lower().strip('[] !@#$%^&*()\"\';:.,/?\\|~`')
    elif isinstance(s, float):
        return np.nan
    else:
        raise Exception("WTF")
books['category'] = books['category'].apply(lambda x: basic_preporcess_category(x))

# 처리하기 전의 category_high
books['category_high'] = books['category'].copy()

books.loc[books[books['category']=='biography'].index, 'category_high'] = 'biography autobiography'
books.loc[books[books['category']=='autobiography'].index,'category_high'] = 'biography autobiography'
books.loc[books[books['category'].str.contains('history',na=False)].index,'category_high'] = 'history'

categories = ['garden','crafts','physics','adventure','music','fiction','nonfiction','science','science fiction','social','homicide',
'sociology','disease','religion','christian','philosophy','psycholog','mathemat','agricult','environmental',
'business','poetry','drama','literary','travel','motion picture','children','cook','literature','electronic',
'humor','animal','bird','photograph','computer','house','ecology','family','architect','camp','criminal','language','india']
for category in categories:
    books.loc[books[books['category'].str.contains(category,na=False)].index,'category_high'] = category

category_high_df = pd.DataFrame(books['category_high'].value_counts()).reset_index()
category_high_df.columns = ['category','count']
others_list = category_high_df[category_high_df['count']<2]['category'].values
books.loc[books[books['category_high'].isin(others_list)].index, 'category_high']='others'
books.drop('category', axis=1, inplace=True)

In [123]:
books['category_high'].value_counts().to_frame()

                                                category_high
fiction                                                 39678
biography & autobiography                                3326
others                                                   2034
history                                                  1949
religion                                                 1824
...                                                       ...
human reproduction                                          2
buffy the vampire slayer (fictitious character              2
guilt                                                       2
baby-sitters club (imaginary organization                   2
photojournalism                                             2

[1232 rows x 1 columns]

In [124]:
path ='./data/'

books = pd.read_csv(path + 'books.csv')
def basic_preporcess_category(s:str):
    if isinstance(s, str):
        return s.lower().strip('[] !@#$%^&*()\"\';:.,/?\\|~`')
    elif isinstance(s, float):
        return np.nan
    else:
        raise Exception("WTF")
books['category'] = books['category'].apply(lambda x: basic_preporcess_category(x))

# 처리하기 전의 category_high
books['category_high'] = books['category'].copy()

books.loc[books[books['category']=='biography'].index, 'category_high'] = 'biography autobiography'
books.loc[books[books['category']=='autobiography'].index,'category_high'] = 'biography autobiography'
books.loc[books[books['category'].str.contains('history',na=False)].index,'category_high'] = 'history'

categories = ['garden','crafts','physics','adventure','music','fiction','nonfiction','science','science fiction','social','homicide',
'sociology','disease','religion','christian','philosophy','psycholog','mathemat','agricult','environmental',
'business','poetry','drama','literary','travel','motion picture','children','cook','literature','electronic',
'humor','animal','bird','photograph','computer','house','ecology','family','architect','camp','criminal','language','india']
for category in categories:
    books.loc[books[books['category'].str.contains(category,na=False)].index,'category_high'] = category

category_high_df = pd.DataFrame(books['category_high'].value_counts()).reset_index()
category_high_df.columns = ['category','count']
others_list = category_high_df[category_high_df['count']<3]['category'].values
books.loc[books[books['category_high'].isin(others_list)].index, 'category_high']='others'
books.drop('category', axis=1, inplace=True)

In [125]:
books['category_high'].value_counts().to_frame()

                                   category_high
fiction                                    39678
biography & autobiography                   3326
others                                      2980
history                                     1949
religion                                    1824
...                                          ...
conservation of natural resources              3
weather                                        3
sports                                         3
monaco                                         3
geography                                      3

[759 rows x 1 columns]

In [126]:
def print_full(x):
    pd.set_option('display.max_rows', 500)
    print(x)
    pd.reset_option('display.max_rows')

In [127]:
print_full(books['category_high'].value_counts().to_frame())

                                   category_high
fiction                                    39678
biography & autobiography                   3326
others                                      2980
history                                     1949
religion                                    1824
...                                          ...
conservation of natural resources              3
weather                                        3
sports                                         3
monaco                                         3
geography                                      3

[759 rows x 1 columns]

In [128]:
(books['category_high'].unique())

array(['actresses', 'others', 'medical', 'fiction', 'history', nan,
       'nature', 'humor', 'cook', 'reference', 'health & fitness',
       'psycholog', 'science', 'conduct of life', 'horses', 'brothers',
       'baggins, frodo (fictitious character',
       'biography & autobiography', 'business', 'americans', 'literary',
       'self-help', 'religion', 'india', 'england', 'social',
       'adolescence', 'dune (imaginary place', 'animal', 'great britain',
       'london (england', 'music', 'fairy tales', 'children', 'jews',
       'arctic regions', 'poetry', 'comics & graphic novels',
       'comic books, strips, etc', 'nonfiction', 'gay men', 'orphans',
       'family', 'computer', 'literature', 'body, mind & spirit', 'women',
       'families', 'criminal', 'games', 'christian', 'presidents',
       'education', 'detective and mystery stories', 'fantasy', 'courage',
       'horror tales', 'feminists', 'philosophy', 'growth', 'astronomy',
       'dinosaurs', 'adventure', 'popular culture',
       'technology & engineering', 'artists', 'kenya',
       'canon (literarature', 'courtship', 'drama', 'language',
       'performing arts', 'exercise', 'glasgow (scotland',
       'arthurian romances', 'sports & recreation', 'journalists',
       'authorship', 'actors', 'science fiction', 'travel',
       'authors, american', 'california', 'pets', 'crafts',
       'berlin (germany', 'covenant, thomas (fictitious character',
       'blind', 'bildungsromans', 'brothers and sisters', 'atomic bomb',
       'dogs', 'detective and mystery stories, english', 'character',
       'dwellings', 'life on other planets', 'alchemists', 'geishas',
       'christmas stories', 'fairies', 'elephants',
       'imaginary wars and battles', 'audiobooks', 'true crime',
       'african american men', 'dent, arthur (fictitious character',
       'cats', 'environmental', 'house', 'extraterrestrial beings',
       'book burning', 'law', 'connecticut', 'relaxation',
       'motion picture', 'abortion', 'bible', 'antiquities', 'classic',
       'japan', 'authors, australian', 'alaska', 'childbirth',
       'man-woman relationships', 'afghanistan', 'audiocassettes',
       'transportation', 'mental illness', 'intelligence service',
       'china', 'creative thinking', 'games & activities', 'art', 'celts',
       'chemistry', 'behavior', 'film novelizations', 'health',
       'authors, spanish', 'cities and towns', 'architect', 'football',
       'horror tales, american', 'friendship', 'dolls', 'espionage',
       'aliens', 'basketball stories', 'electronic', 'divorce',
       'feminism', 'northern ireland', 'soldiers', 'catholics',
       'hispanic american women', 'lesbians', 'disease', 'elves',
       'horror', 'interplanetary voyages', 'anthropologists',
       'boston (mass', 'hallucinogenic drugs and religious experience',
       'communication', 'deviant behavior', 'los angeles (calif',
       'artificial intelligence', 'brooklyn (new york, n.y', 'dragons',
       'imaginary places', 'krynn (imaginary place', 'photograph',
       'death', 'anglo-saxons', 'badgers', 'fathers and sons', 'boys',
       'camp', 'ecology', 'alice (fictitious character : carroll',
       'united states', 'copenhagen (denmark', 'new york (n.y',
       'dracula, count (fictitious character', 'whales',
       'amelia-bedelia (fictitious character', 'child rearing',
       'riddles, juvenile', 'chickens', 'authors', 'angels',
       'apologetics', 'aunts', 'technology', 'allegories', 'russia',
       'adultery', 'african americans', 'mathemat',
       'interpersonal relations', 'country life', 'world war, 1939-1945',
       'low-calorie diet', 'entertaining', 'france', 'ants',
       'spiritual life', 'cancer', 'argentina', 'castaways', 'arithmetic',
       'blizzards', 'murder', 'accidents',
       'brunetti, guido (fictitious character', 'barcelona (spain',
       'cheerleading', 'africa', 'alberta', 'androids', 'germany',
       'biographers', 'south africa', 'robots', 'authors, english',
       'magic', 'legislators', 'amnesia', 'arizona', 'advice columnists',
       'love stories', 'oceania', 'australia', 'life',
       'ahab, captain (fictitious character', 'cowboys',
       'biography autobiography', 'anecdotes', 'chocolate', 'ethics',
       'tarot', 'garden', 'amerikan romanı', 'college stories',
       'human-alien encounters', 'babysitters', 'paris (france',
       'comedians', 'antiques & collectibles', 'chile', 'study aids',
       'food', 'blake, anita (fictitious character', 'assassins',
       'acting', 'extrasensory perception', 'amsterdam (netherlands',
       'diaries', 'boarding schools', 'aboriginal australians', 'canada',
       'ghost stories', 'african american authors', 'city and town life',
       'design', 'avarice', 'folklore', 'atlantis (legendary place',
       'caricatures and cartoons', 'finance, personal',
       'civilization, modern', 'balloons', 'african american women',
       'names, personal', 'high school students', 'astronautics',
       'marriage service', 'dance', 'amish', 'british', 'jerusalem',
       'authors, french', 'bears', 'circus', 'books and reading',
       'left- and right-handedness', 'dysfunctional families',
       'art forgers', 'large type books', 'crime', 'birthdays',
       'government investigators', 'hell', 'short stories', 'girls',
       'blacks', 'serial murders', 'beauty, personal', 'portugal',
       'sonnets, english', 'holocaust, jewish (1939-1945', 'bibles',
       'plot-your-own stories', 'braille books', 'men',
       'accelerated readers', 'veterinarians', 'clue (game', 'schools',
       'homeless persons', 'sea stories', 'belgians', 'joy', 'clubs',
       'vampires', 'dreams', 'automobiles', 'christmas decorations',
       'devotional calendars', 'cornwall (england : county', 'coma',
       'mexico', 'ireland', 'happiness', 'arkansas', 'anger',
       'curiosities and wonders', 'love stories, american', 'halloween',
       'almanacs, american', 'adoption', 'communication in marriage',
       'charity-schools', 'bashfulness', 'editing', 'career changes',
       'encyclopedias and dictionaries', 'alcoholics', 'bird', 'novel',
       'butterflies', 'discworld (imaginary place', 'aging', 'physics',
       'medicine, popular', 'kidnapping', 'grandmothers', 'airplanes',
       'caribbean area', 'police', 'entertainers', 'bereavement', 'devil',
       'amyotrophic lateral sclerosis', 'colombia', 'buddhism',
       'unidentified flying objects', 'mothers and daughters',
       'short stories, american', 'museums', 'composers', 'chicago (ill',
       'abduction', 'maori (new zealand people', 'leukemia',
       'astral projection', 'castles', 'capitalism',
       'frontier and pioneer life', 'antisemitism',
       'employment interviewing', 'investments', 'baseball',
       'horror stories', 'depressions', 'nuclear warfare', 'brain',
       'behavior modification', 'baltimore (md', 'academic writing',
       'consumption (economics', 'egypt', 'antarctica', 'cousins',
       'archaeology', 'adult child abuse victims', 'cuba', 'louisiana',
       'stories in rhyme', 'cambridge (england', 'bats',
       'decker, peter (fictitious character',
       'capitalists and financiers', 'healing', 'mafia', 'good and evil',
       'heroes', 'western stories', 'identity (philosophical concept',
       'conspiracies', 'readers', 'contests', 'antiques', 'denmark',
       'deer', 'emotions', 'twins', 'food habits', 'high schools',
       'amusements', 'abused wives', 'private investigators',
       'horse racing', 'baseball stories', 'drug abuse',
       'overland journeys to the pacific', 'fear',
       'african american families', 'amusement parks',
       'dream interpretation', 'fathers', 'edinburgh (scotland', 'clowns',
       'dalmatian dog', 'mothers and sons', 'rabbits', 'fishes',
       'beauty contests', 'authors, irish', 'god', 'depression glass',
       'radio', 'consumer education',
       'dalgliesh, adam (fictitious character', 'sex',
       'cotswold hills (england', 'soccer', 'biology', 'new zealand',
       'marketing', 'child care', 'art, modern', 'female friendship',
       'austria', 'highlands (scotland', 'italy', 'authors, german',
       'merlin (legendary character', 'mythology, classical',
       'generation x', 'africa, north', 'antique dealers', 'trojan war',
       'druids and druidism', 'blindness', 'cathedrals', 'hiking',
       'christmas', 'accident victims', 'college students', 'spain',
       'beaches', 'alphabet', 'mystery and detective stories',
       'aphrodisiacs', 'puzzles', 'medical examiners (law', 'ghosts',
       'brazil', 'authors, austrian', 'alcoholism', 'cults',
       'celebrities', 'meditation', 'homicide',
       'hollywood (los angeles, calif', 'child abuse', 'aromatherapy',
       'blessing and cursing', 'asterix (fictitious character',
       'generals', 'corporate culture', 'father and child',
       'quotations, english', 'massachusetts', 'child development',
       'advertising', 'roman policier', 'farm life', 'success',
       'missing persons', 'erotic stories', 'cruise ships', 'ex-convicts',
       'drugs', 'monaco', 'sports', 'weather',
       'conservation of natural resources', 'herbs', 'epidemics',
       'prophecies (occultism', 'cambodia', 'rio de janeiro (brazil',
       'europe', 'folk medicine', 'diabetes', 'culture conflict',
       'mountaineering', 'american essays', 'greece',
       'baggins, bilbo (fictitious character',
       'middle earth (imaginary place', 'alternative medicine',
       'teddy bears', 'discoveries in geography', 'multiple personality',
       'alchemy', 'outlaws', 'quotations', 'fort lauderdale (fla',
       'bullies', 'college readers', 'sisters', 'love', 'hawaii',
       'demonology', 'hotels', 'painters', 'autumn', 'executive ability',
       'forgiveness', 'erotic stories, american', 'aeronautics',
       'handicraft', 'cross-stitch', 'africa, west',
       'dungeons and dragons (game', 'internet', 'san francisco (calif',
       'questions and answers', 'animated films', 'insects',
       'best friends', 'glow-in-the-dark books', 'cosmology',
       'communication in management', 'murderers', 'adoptees',
       'easter stories', 'inventions', 'hockey stories', 'frogs',
       'ballet', 'arab-israeli conflict', 'authors, brazilian',
       'babar (fictitious character', 'mice', 'feng shui', 'babies',
       'emperors', 'air pilots', 'beresford, tommy (fictitious character',
       'clothing and dress', 'applications for positions', 'ambassadors',
       'algeria', 'ducks', 'clifford (fictitious character : bridwell',
       'management', 'common fallacies', 'horror tales, english',
       'belden, trixie (fictitious character', 'baby sitters',
       'information technology', 'chess', 'psychoanalysis',
       'civilization, medieval', 'future life', 'reincarnation',
       'manners and customs', 'eskimos', 'do-it-yourself work',
       'creative writing', 'readers (primary', 'infants',
       'belfast (northern ireland', 'desktop publishing',
       'athens (greece', 'midlife crisis', 'deception',
       'cartoon characters', 'drawing', 'theater',
       'leia, princess (fictitious character', 'apartheid', 'clergy',
       'administration of estates', 'obesity', 'colorado', 'counting',
       'attention-deficit hyperactivity disorder', 'country homes',
       'world war, 1914-1918', 'arranged marriage', 'parenting',
       'prayers', 'mothers', 'soccer players', 'teenage girls',
       'fathers and daughters', 'executives', 'consolation', 'cat breeds',
       'armageddon', 'bullying', 'bedtime', 'anorexia nervosa', 'atlases',
       'animation (cinematography', 'easter eggs', 'body, human',
       'napoleonic wars, 1800-1815', 'coal miners', 'puppets',
       'bible stories', 'bible stories, english',
       'ghost stories, american', 'fossils', 'chinese americans',
       'dolphins', 'metamorphosis', 'iran', 'advertising, direct-mail',
       'home economics', 'almanacs', 'civil rights', 'florida', 'gangs',
       'basketball', 'belief and doubt', 'earthquakes', 'drug traffic',
       'montana', 'brown, encyclopedia (fictitious character',
       'picture books', 'vocabulary', 'human body', 'sharing',
       'outer space', 'scotland', 'sat (educational test',
       'wine and wine making', 'chronology, historical', 'criticism',
       'beat generation', 'heart',
       'detective and mystery stories, american',
       'klondike river valley (yukon', 'consciousness',
       "presidents' spouses", 'washington (d.c', 'space and time',
       'mexican americans', 'books', 'current events', 'botany',
       'astrology', 'short stories, english', 'board books',
       'supernatural', 'reading', 'charms', 'journalism', 'idaho',
       'evolution (biology', 'foreign correspondents', 'mythology',
       'human beings', 'bars (drinking establishments', 'cricket',
       'radio broadcasters', 'vietnam war, 1961-1975',
       'achievement motivation', 'etiquette', 'forensic psychiatry',
       'automatic bread machines', 'knights and knighthood',
       'bicycle touring', 'archaeologists', 'fables', 'economics',
       'sociology', 'color', 'asia', 'antiquities, prehistoric',
       'beverages', 'occultism', 'football players', 'diet',
       'tongue twisters', 'soviet union', 'child psychotherapy',
       'mammals', 'marriage', 'bombing, aerial', 'career development',
       'indonesia', 'anthropology', 'excavations (archaeology',
       'cave dwellers', 'running', 'genealogy', 'college teachers',
       'self-realization', 'commercial statistics', 'bread',
       'dublin (ireland', 'examinations', 'anxiety', 'civilization',
       'latin america', 'assassination', 'teenagers', 'prayer', 'moon',
       'buried treasure', 'conflict of generations', 'city planning',
       'cliffs notes', 'golf', 'interior decoration', 'fantasy games',
       'kings and rulers', 'time management', 'ghost stories, english',
       'authors, dutch', 'globalization', 'time', 'arts and society',
       'singers', 'flatulence', 'communism', 'beanie babies (trademark',
       'terrorism', 'origami', 'borrowers (fictitious characters',
       'culture', 'inheritance and succession', 'monsters',
       'graphic novels', 'beatitudes',
       'bolan, mack (fictitious character', 'heads of state', 'ethnology',
       'culture shock', 'forecasting', 'canon law', 'agricult',
       'geography'], dtype=object)

In [7]:
for cat, cnt in books['category_high'].value_counts().to_dict().items():
    print(cat, cnt)

fiction 39678
others 4136
biography & autobiography 3335
history 1949
religion 1824
nonfiction 1427
humor 1291
social 1271
business 1146
cook 1125
body, mind & spirit 1113
science 1063
family 988
health & fitness 971
literary 848
computer 806
language 804
poetry 740
psycholog 729
travel 672
self-help 640
art 563
drama 537
children 525
philosophy 491
nature 490
reference 471
performing arts 457
sports & recreation 446
comics & graphic novels 422
crafts 413
music 365
education 339
true crime 336
pets 306
garden 294
detective and mystery stories 257
medical 243
animal 225
adventure 208
house 203
photograph 175
literature 174
technology & engineering 161
christian 138
architect 129
games & activities 128
science fiction 128
games 125
law 104
india 98
antiques & collectibles 97
friendship 84
brothers and sisters 84
cats 83
motion picture 76
mathemat 73
families 71
bible 67
england 65
australia 64
fantasy 63
adolescence 62
design 62
great britain 56
fairy tales 53
authors, american 52
african americans 49
actors 47
dogs 47
conduct of life 47
france 46
horror tales 46
transportation 44
adultery 41
murder 41
criminal 39
city and town life 38
camp 38
united states 37
brothers 37
bears 36
bibles 35
christmas stories 35
canada 35
country life 34
dinosaurs 34
authors, english 34
babysitters 33
disease 32
africa 32
americans 32
comic books, strips, etc 32
man-woman relationships 30
curiosities and wonders 30
angels 30
artists 30
british 27
bird 26
child rearing 26
china 26
death 25
electronic 25
crime 25
ghost stories 25
boarding schools 24
egypt 23
horror stories 23
germany 23
arthurian romances 23
study aids 23
boys 22
authorship 22
interplanetary voyages 21
short stories 19
ireland 19
behavior 18
california 18
love 18
london (england 18
interpersonal relations 18
extraterrestrial beings 18
authors 17
europe 17
aunts 17
frontier and pioneer life 17
ecology 17
love stories 17
buddhism 17
blind 17
bereavement 16
divorce 16
folklore 16
books and reading 16
feminism 15
high schools 15
magic 15
alcoholics 15
ghosts 15
caricatures and cartoons 14
fantasy games 14
childbirth 14
alternative medicine 14
large type books 14
clubs 14
paris (france 14
child development 14
composers 14
christmas 14
dragons 14
aboriginal australians 14
horror tales, american 14
boston (mass 14
authors, german 14
health 13
plot-your-own stories 13
holocaust, jewish (1939-1945 13
lesbians 13
birthdays 13
dune (imaginary place 13
detective and mystery stories, english 13
environmental 13
berlin (germany 13
new york (n.y 13
mothers and daughters 12
schools 12
baseball 12
novel 12
counting 12
dream interpretation 12
vampires 12
actresses 12
courtship 12
presidents 12
horses 12
baggins, frodo (fictitious character 12
world war, 1939-1945 12
life on other planets 12
journalists 12
tarot 11
african american women 11
authors, french 11
amsterdam (netherlands 11
encyclopedias and dictionaries 11
discworld (imaginary place 11
exercise 11
finance, personal 11
readers 11
hollywood (los angeles, calif 11
cancer 11
russia 11
cults 11
alphabet 11
women 11
beauty, personal 10
college students 10
bedtime 10
intelligence service 10
brazil 10
dreams 10
archaeology 10
fairies 10
herbs 10
chicago (ill 10
celebrities 10
home economics 10
cornwall (england : county 10
courage 10
arizona 10
quotations, english 9
fathers and daughters 9
halloween 9
astronomy 9
civilization, medieval 9
accelerated readers 9
physics 9
mystery and detective stories 9
acting 9
girls 9
drug abuse 9
jews 9
astrology 9
child care 9
gay men 9
avarice 9
dracula, count (fictitious character 9
dwellings 9
anger 9
arctic regions 9
circus 9
bible stories, english 8
antiques 8
fathers and sons 8
bildungsromans 8
college readers 8
aging 8
handicraft 8
good and evil 8
elephants 8
covenant, thomas (fictitious character 8
adoption 8
audiobooks 8
chile 8
monsters 8
brain 8
authors, australian 8
dolls 8
italy 8
scotland 8
castaways 8
high school students 8
communication 8
artificial intelligence 8
soccer 8
audiocassettes 8
mice 8
alaska 8
african american men 8
assassins 8
veterinarians 8
fear 8
devotional calendars 8
clothing and dress 8
manners and customs 8
spiritual life 7
human-alien encounters 7
generals 7
cousins 7
apologetics 7
african american families 7
aromatherapy 7
horse racing 7
color 7
meditation 7
spain 7
college teachers 7
economics 7
homicide 7
child abuse 7
erotic stories, american 7
adoptees 7
aeronautics 7
dent, arthur (fictitious character 7
consciousness 7
arab-israeli conflict 7
board books 7
food 7
journalism 7
abortion 7
sisters 7
police 7
unidentified flying objects 7
comedians 7
cities and towns 7
advertising 7
infants 6
bible stories 6
executives 6
singers 6
drawing 6
sat (educational test 6
mythology 6
civilization 6
air pilots 6
hiking 6
orphans 6
cosmology 6
sociology 6
asterix (fictitious character 6
farm life 6
almanacs 6
accidents 6
amusements 6
antisemitism 6
biology 6
cowboys 6
chocolate 6
catholics 6
african american authors 6
christmas decorations 6
entertainers 6
chickens 6
arkansas 6
horror 6
blake, anita (fictitious character 6
kidnapping 6
medicine, popular 6
extrasensory perception 6
diaries 6
aliens 6
castles 6
amnesia 6
brunetti, guido (fictitious character 6
consumer education 6
japan 6
celts 6
robots 6
names, personal 6
ants 6
canon (literarature 6
emotions 6
contests 6
conspiracies 6
stories in rhyme 6
antarctica 6
bashfulness 6
outer space 5
elves 5
detective and mystery stories, american 5
authors, spanish 5
chemistry 5
arranged marriage 5
criticism 5
vietnam war, 1961-1975 5
current events 5
soviet union 5
inheritance and succession 5
cheerleading 5
kings and rulers 5
interior decoration 5
city planning 5
buried treasure 5
diet 5
brooklyn (new york, n.y 5
ethics 5
fables 5
bicycle touring 5
achievement motivation 5
government investigators 5
idaho 5
country homes 5
female friendship 5
colorado 5
clergy 5
devil 5
greece 5
colombia 5
atomic bomb 5
cruise ships 5
missing persons 5
success 5
abduction 5
depressions 5
abused wives 5
baseball stories 5
authors, austrian 5
clowns 5
mothers and sons 5
rabbits 5
god 5
beaches 5
bullies 5
caribbean area 5
grandmothers 5
feng shui 5
athens (greece 5
classic 5
antiquities 5
homeless persons 5
chess 5
applications for positions 5
relaxation 5
mexico 5
autumn 5
ballet 5
frogs 5
communication in marriage 5
questions and answers 5
internet 5
alchemists 5
executive ability 5
ducks 5